### ISSUE TITLE
tmc-603

### ISSUE THREAD

**Issue by FPGAy** [trinamic/TMC-API#15]
Is there an c api for tmc-603 ? I am using tmcm-1640 and i was searching for a c library.

**Comment by trinamic-ed** [comment]
Hi,

there is no direct c api for the TMC603, because it has no SPI interface. The TMC603 is discontinued (https://www.trinamic.com/support/help-center/old-products/discontinued/tmc603a-la/), so for new designs please use the TMC6140. For the TMC6140, c code examples to use the driver are available here: https://github.com/trinamic/TMC-EvalSystem/blob/master/boards/TMC6140_eval.c

Best regards,
     Enrico
